server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://root:root@localhost:3306/pizzarch
